services:
    app:
        build:
            context: ./CSME
            dockerfile: DockerFile
        container_name: CSME
        env_file:
            - ./variable/app.env
        ports:
        - "8080:8080"
        networks:
            - private
        secrets:
        - postgres_password
        # change for prod
        volumes:
            - ./CSME/src:/app/src
        healthcheck:
            test: ["CMD", "httpcheck", "http://localhost:8080/"]
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 30s
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
            memcached:
                condition: service_healthy
        # change for prod
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
    
    postgres:
        image: postgres:17-alpine
        container_name: postgres
        networks:
        - private
        environment:
        - POSTGRES_DB=my_db
        - POSTGRES_USER=my_user
        - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
        - postgres_password
        volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:read_only
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 15s
        restart: unless-stopped
        # change for prod
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    memcached:
        image: memcached:1.6-alpine
        container_name: memcached
        networks:
        - private
        read_only: true
        # change for prod
        command: ["memcached", "-m", "128"]  # set the memory to 128 MB
        stop_grace_period: 15s
        healthcheck:
            test: echo stats | nc localhost 11211
            interval: 15s
            timeout: 10s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        # change for prod
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

volumes:
    postgres_data:
        name: postgres_db

secrets:
    postgres_password:
        file: ./variable/postgres_password.txt

networks:
    private:
        driver: bridge
