FROM python:3.13-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.11.3 /uv /uvx /bin/
COPY --from=ghcr.io/tarampampam/microcheck:1 /bin/httpcheck /bin/httpcheck

WORKDIR /app

COPY uv.lock pyproject.toml /app/
ENV UV_NO_DEV=1
RUN uv sync --locked --no-cache && \
    rm uv.lock pyproject.toml

COPY /src ./src

WORKDIR /app/src
# prod
# RUN groupadd -r appgroup && useradd -r -g appgroup -m appuser
# USER appuser
CMD ["/app/.venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"] # change for prod